puppetlabs/puppetlabs-reboot

- .travis.yml
- Gemfile
Allowing Travis to run on other branches can simplify development by catching test failures before a pull request is made.
> Travis improvements: run on non-master branches, build on Ruby 1.8.7, and reduce build times

- lib/puppet/provider/reboot/linux.rb
- spec/unit/provider/reboot/linux_spec.rb
Linux uses minutes to specify its shutdown timeout, but the :timeout parameter is in seconds. Ruby uses integer division, so previously values of `:timeout` that weren't whole multiples of 60 would be rounded down. This changes the behavior so that they are rounded up and a warning is issued notifying the user.
> (MODULES-1729) Round :timeout up to the nearest minute and warn

- README.md
- lib/puppet/provider/reboot/windows.rb
- lib/puppet/type/reboot.rb
- metadata.json
- spec/unit/provider/reboot/windows_spec.rb
- spec/unit/type/reboot_spec.rb
- tests/sample.pp
[JIRA ticket here](https://tickets.puppetlabs.com/browse/MODULES-1638).  This also bumps the version to 0.2.0-SNAPSHOT as it is a breaking change.
> (MODULES-1638) Remove prompt parameter

- lib/puppet/provider/reboot/windows.rb
- lib/puppet/type/reboot.rb
- spec/unit/provider/reboot/windows_spec.rb
- spec/unit/type/reboot_spec.rb
As per [MODULES-1730](https://tickets.puppetlabs.com/browse/MODULES-1730), if multiple reboot resources attempt to schedule a reboot, the system's shutdown command is executed multiple times.  If it doesn't check for this, unexpected behavior can result.  This adds a check that the shutdown command is only scheduled once by the reboot type.
> (MODULES-1730) Only run the shutdown command once

- acceptance/setup/install_modules.rb
Ensure module is removed from linux nodes before installing
Change to copy_root_module_to as the other does not work on windows systems due to CA issues
> Fix reboot spec tests

- acceptance/tests/posix/reboot_message.rb
- acceptance/tests/windows/reboot_message.rb
- lib/puppet/type/reboot.rb
- spec/unit/type/reboot_spec.rb
As requested in [MODULES-1724](https://tickets.puppetlabs.com/browse/MODULES-1724), this will allow external processes to identify if a reboot was initiated by Puppet.
> (MODULES-1724) Emit notice when scheduling reboot

- README.md
- acceptance/lib/helper.rb
- acceptance/tests/linux/reboot_finished.rb
- acceptance/tests/linux/reboot_immediate.rb
- acceptance/tests/linux/reboot_immediate_explicit.rb
- acceptance/tests/linux/reboot_message.rb
- acceptance/tests/linux/reboot_no_refresh.rb
- acceptance/tests/linux/reboot_refreshed_explicit.rb
- acceptance/tests/linux/reboot_resume.rb
- acceptance/tests/linux/reboot_skip.rb
- acceptance/tests/linux/reboot_timeout.rb
- acceptance/tests/posix/reboot_timeout.rb
- lib/puppet/provider/reboot/linux.rb
- spec/unit/provider/reboot/linux_spec.rb
This adds a deprecated `linux` provider stub and enables one of the acceptance tests for Solaris that was disabled for, as it turns out, no good reason.
> (MODULES-1977) Fix problems with POSIX provider

- .sync.yml
- Gemfile
Further restrict down the restrictions on windows dependencies when
using older Puppet versions, such that it works with Puppet 3.0.0 -
3.7.0. It does require a bit more logic in selecting gems but it allows
for testing older platforms without any additional known issues for
Puppet versions under 3.4.0.
> (MODULES-2207) Gem restrictions for Older puppet versions

- acceptance/tests/windows/reboot_pending.rb
- lib/puppet/provider/reboot/windows.rb
- spec/unit/provider/reboot/windows_spec.rb
- A pending computer rename operation is a trigger for a reboot, even
though it is not expressed in any of the existing checks.
This is due to the fact that the Windows API GetComputerName function
reads the NetBIOS name of the computer from the registry on first boot
and caches it for all of eternity.  See docs at:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724295(v=vs.85).aspx
> (MODULES-2657) Detect Windows computer rename

- lib/puppet/provider/reboot/windows.rb
- Prior commits failed to add appropriate debug messages to notify
what system settings were responsible for setting a system reboot
state.
> (maint) Emit Windows debug messages for pending

- lib/puppet/provider/reboot/windows.rb
- spec/unit/provider/reboot/windows_spec.rb
- Adds a new value to the Windows specific provider implementation that
can be set to notify of a pending reboot.
- This has been added primarily for the sake of DSC, which needs a way
to ask for a reboot on demand, since the Invoke-DscResource cmdlet in
PowerShell does not propagate a global status anywhere.
See https://tickets.puppetlabs.com/browse/MODULES-2641
Sample usage from within another module looks something like:
resource.catalog.resource(:reboot, 'dsc_reboot')
if reboot_resource.provider.respond_to?(:reboot_required)
reboot_resource.provider.reboot_required = true
else
> (MODULES-2822) Windows provider reboot_required

- spec/unit/provider/reboot/windows_spec.rb
- In cases where the system is actually pending a reboot for reasons
other than setting the `reboot_required` flag, the module would report
a reboot.
Guard against these conditions, by adjusting tests.
> (MODULES-2822) Adjust reboot_required specs

- Gemfile
We don't use DevKit in CI, so it should not be required for
normal testing purposes.
> (maint) update modsync / fix build

- lib/puppet/provider/reboot/windows.rb
- `and` is a control flow construct, not one that should be used for
boolean conditionals like `&&`
> (maint) Use appropriate conditionals

- appveyor.yml
- lib/puppet/provider/reboot/windows.rb
This reverts commit 05b7ce404b0b3fd5b2cfd4b88e864f1445626d2a.
During acceptance testing it was found that this causes issues
in particular versions of Ruby. So we'll move back to control
flow conditionals for now.
> Revert "(maint) Use appropriate conditionals"

- Rakefile
The rakefile is attempting to override the default puppet lint settings however
these settings are more permissive than the defaults and are causing false
lint failures e.g. the vendor directory is not excluded in thie Rakefile but
the puppetlabs_spec_helper does this by default.  This commit removes the
ignore_paths setting as the spec helper already does this.  Also added a comment
that the 80 and 140 char rule changes can be removed once next version of
spec_helper is released as they are already the defaults.
> (maint) Update rakefile for puppetlabs_spec_helper

- .sync.yml
- Gemfile
- spec/unit/provider/reboot/windows_spec.rb
The gem specification for mimetypes was causing an old version of beaker to be installed.
This version of beaker is not compatible with 2016.2 as it is unable to use the beaker-answers
gem as 2016.2 is installed using MEEP.  The mimetypes specification appears to be a hold over
from copying sync.yml from the acl project.  This commit keeps the nokogiri gem requirement
but uses the optional gems notation in the sync.yml so that the defaults from modsync still
get applied.
This commit also updates Gemfile with modsync.
Previously RSpec was pinned to an old version (2.x) however this is no longer
the case.  Three tests were causing CI failures due to using the older should
syntax.  This commit updates these tests using the newer expect syntax.
> (maint) Update module for use with PE 2016.2

- README.md
- lib/puppet/provider/reboot/windows.rb
- lib/puppet/type/reboot.rb
- spec/unit/provider/reboot/windows_spec.rb
- spec/unit/type/reboot_spec.rb
When we set `when => pending`, there are a number of events that will
cause a reboot.
Introduce `onlyif` and `except` so we can filter on the events we care
about.
> (MODULES-4328) Implement reboot reason for windows

- Rakefile
The acceptance tests for Reboot are written in standard beaker format however
the preferred method is using beaker-rspec.  This commit overrides the
default `beaker` task, which would normally use beaker-rspec, and instead
invokes beaker directly.  This is only need while the module tests are migrated
to the newer rspec-beaker format.
> (maint) Modify beaker task to simulate direct beaker invocation

- .sync.yml
- Gemfile
As per Github, there is a known security issue in nokogiri < 1.8.1 . I was not sure if removing the pin was ok so I just bumped it to ~> 1.8.1 in .sync.yml and the Gemfile.
> (maint) bump nokogiri pin

- metadata.json
- spec/spec_helper_acceptance.rb
Moved the test dependencies of stdlib and registry from metadata.json to install from the forge via a beaker on(host) call inside of spec_helper_acceptance.
> (MAINT) move test dependences from metadata to spec_helper_acceptnace

- metadata.json
Previously the OS compatibility metadata was not correct.  This commit aligns
the OS list with the puppetlabs-stdlib module, in particular the Windows OS
list.
> (MODULES-6443) Update OS compatibility metdata

- CHANGELOG.md
Prior to this commit the `puppetlabs-reboot` project used
a custom changelog format. This maintenance commit updates
the changelog to follow the KeepAChangelog standard and
adds the unreleased section to the top of the changelog.
> (MAINT) Update changelog to KAC standard

- CHANGELOG.md
- metadata.json
It is entirely possible this will need to be updated prior to merge. I'm not sure `1.3.0` is the appropriate version given the underlying dependency and platform updates.
> (MODULES-6443) Prep for v2.0.0 release

- lib/puppet/provider/reboot/linux.rb
- lib/puppet/provider/reboot/posix.rb
- lib/puppet/provider/reboot/windows.rb
- lib/puppet/type/reboot.rb
- spec/acceptance/reboot_finished_spec.rb
- spec/acceptance/reboot_immediate_spec.rb
- spec/acceptance/reboot_message.spec.rb
- spec/acceptance/reboot_no_refresh_spec.rb
- spec/acceptance/reboot_pending_spec.rb
- spec/acceptance/reboot_resume_spec.rb
- spec/acceptance/reboot_skip_spec.rb
- spec/acceptance/reboot_timeout_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/unit/provider/reboot/linux_spec.rb
- spec/unit/provider/reboot/posix_spec.rb
- spec/unit/provider/reboot/windows_spec.rb
- spec/unit/type/reboot_spec.rb
- tasks/init.rb
Previously rubocop was not enforced on ruby code.  This commit fixes the
existing rubocop violations in preparation for enabling rubocop in CI.  This
commit uses the rubocop configuration which was deployed in PDK template
1.3.2-0-g07678c8.
> (MODULES-5896)(MODULES-3975) Fix rubocop violations

- .sync.yml
Without this commit, modsync will fail to parse this module as the name of the
travis file is actually `.travis.yml`.
> (maint) Fix typo in for travis yaml file

- .sync.yml
- Gemfile
- spec/acceptance/reboot_finished_spec.rb
- spec/acceptance/reboot_immediate_spec.rb
- spec/acceptance/reboot_message.spec.rb
- spec/acceptance/reboot_no_refresh_spec.rb
- spec/acceptance/reboot_pending_spec.rb
- spec/acceptance/reboot_resume_spec.rb
- spec/acceptance/reboot_skip_spec.rb
- spec/acceptance/reboot_timeout_spec.rb
- spec/spec_helper_acceptance.rb
This commit adds the necessary entries to the acceptance setup in order
for testmode switcher to work
This commit updates all host execution methods to execute_manifest_on methods.
Where applicable, it changes explicit exitcode calls to catch_failures or
catch_changes.
> (MODULES-6745) Add testmode to tests

- spec/acceptance/reboot_pending_spec.rb
- spec/acceptance/reboot_resume_spec.rb
This change converts the last few calls to the old beaker manifest
helper functions over to the preferred beaker-testmode_switcher helper
functions.
> (MODULES-6745) Use testmode-switcher

- .sync.yml
- Gemfile
- appveyor.yml
- metadata.json
This commit updates the metadata to show support for Puppet 6 and updates the
testing matrix.
> (MODULES-7832) Update module for Puppet 6

- tasks/last_boot_time.sh
Use the `-F` option for `last` when available to get a time with
seconds, but if it errors fallback to `last` without `-F`.
Fixes tests on EL 5 systems.
> (BOLT-957) Make last_boot_time task more portable

- README.md
- tasks/last_boot_time_nix.json
- tasks/last_boot_time_win.json
Add required versions of Bolt and PE for the reboot plan. Also make the extra implementations of last_boot_time private so that tools that support implementations and the private key only show a single task.
> (maint) Add useful metadata for the reboot plan and last_boot_time tasks

- .sync.yml
This change should mean that the next time pdk update is run the `if`
block that loads the `bolt` and `beaker-task_helper` into `if`
conditionals on their own lines. This way the `if` block doesn't have
to be added to the Gemfile by hand after each update.
> (MAINT) Fix hand crafting the gemfile.

- spec/acceptance/tasks/init_spec.rb
Previously, the tests were omitting the `params` argument to `run_task`.
In newer versions of BoltSpec, that parameter is going to be required,
so now we always pass it.
> (BOLT-1057) Pass required args to run_task

- .rubocop.yml
- .sync.yml
- .travis.yml
- Gemfile
- spec/plans/init_spec.rb
Prior to this change the unit tests for the reboot Bolt plan was not
working properly. The broken tests were not noticed because the
.travis.yml file was not configured to run the tests.
This change ensures that the tests function properly and that Travis
is properly configured to execute the tests on pull requests.
> (MAINT) Fix Plan Unit Tests

- spec/acceptance/tasks/init_spec.rb
- spec/spec_helper_acceptance.rb
Moving the requires causing dependancy issues to the spec_helper_acceptance so they don't conflict with each other.
> (MODULES-8717) Fix dependency issue on boltspec

- tasks/nix.sh
Since reboot task is running shutdown command on a nohup, if its run as a normal user it will silently fail. This change will avoid that.
> [MODULES-8718] Check for root or sudo in the reboot task nix.sh script

- tasks/nix.sh
The shutdown command is usually in /sbin or /usr/sbin.  Many normal
users don't already have them in their path.
Running bolt task run reboot -n somenode --run-as root doesn't reboot
the server, but does return a success.
Add /usr/sbin and /sbin to the path in the nix.sh script
> MODULES-8726: Ensure sbin is in the path

- tasks/nix.sh
Observing some weird race-condition-y behaviors where the nix.sh script
previously was not reliable in rebooting systems. Most of the time with
an attached TTY, the subprocess was still being killed when the
TTY-attached parent shell terminated.
Adding a `sync` call seems to work around the problem.
Adding an explicit `disown` for linux just for completeness. It was not
shown to help with the observed race condition, which is resoseems to
work around the problem.
Adding an explicit `disown` for linux just for completeness. It was not
shown to help with the observed race condition (which is resolved by
`sync`). `disown` is a bash built-in, and this is a bash script so we
should be fine to use it.
> Add additional guards for nix process detach

- README.md
- plans/init.pp
- spec/plans/init_spec.rb
Assuming some nodes successfully reboot and some nodes don't, when the
reboot plan is invoked with `_catch_errors => true`, it should return
meaningful data so that the end user can decide how to handle or report
on which nodes failed to reboot while potentially continuing forward
to another task with the set of nodes that succeeded.
This commit makes the reboot plan always return meaningful data, even
when erroring.
> Fix plan return value

- spec/unit/task/init_spec.rb
- tasks/init.json
- tasks/init.rb
- tasks/nix.json
- tasks/nix.sh
- tasks/win.json
- tasks/win.ps1
Adds the `shutdown_only` parameter which allows shutting down of servers without a reboot (for decommissioning workflows, cloud etc).
Adds ✨ automated unit tests ✨ for the task 😮
> Add `shutdown_only` parameter to tasks

- README.md
- lib/puppet/provider/reboot/windows.rb
- lib/puppet/type/reboot.rb
- spec/unit/provider/reboot/windows_spec.rb
Add an option to the module that checks if there is a pending reboot due to a domain join.  This will allow flexibility when puppet is not only joining a server to the domain but also installing software that will trigger a reboot due to software installation.  This is especially useful when provisioning servers thru something like Cloudbolt and having a system reboot in the middle of a run will cause failures.
> (MODULES-8201) Add pending reboot due to domain join for windows.

- README.md
- plans/init.pp
- spec/plans/init_spec.rb
This changes the `$nodes` parameter for the `reboot` plan to `$targets`
as part of a larger change to Bolt's bundled content.
Part of https://github.com/puppetlabs/bolt/issues/1376
> (GH-1376) Change `$nodes` parameter for `reboot` plan to `$targets`

- plans/init.pp
- spec/plans/init_spec.rb
Given the default log level for bolt will not surface this and the fact that out::message will be surfaced in the PE console when running plans in PE (no puppet log functions go to console, just to orchestration-services.log) prefer out::message to notice.
> (maint) Prefer out::message to notice

- plans/init.pp
The reboot task (that gets run in line 30) always returns the status and timeout. The timeout is (per definition) the max between 3 and $reboot_delay. No real dynamic output that is generated by the reboot task is used in the plan.
Hence: We can default to a $wait for the maximum of 3 or $reboot_delay. This way it does not matter to the plan what the reboot task runs. So broadcast-messages (and possibly other things) do not interfere with the parsing of the timeout.
> (MODULES-10955) More robust handling of reboot-task output

- tasks/init.rb
Puppet 7 dropped the dependency on win32-process gem
in favour of monkey patching the Process Module.
As a repercussion, require `win32/process` will no
longer work on Puppet >= 7.0.0.
This commit updates the reboot task to only require
that specific gem if Puppet < 7.0.0
Enabled and run the test that were filtered out:
```
Finished in 12 minutes 49 seconds (files took 2.06 seconds to load)
14 examples, 2 failures
Failed examples:
rspec ./spec/acceptance/tasks/init_spec.rb:17 # reboot task reboots a target
rspec ./spec/acceptance/tasks/init_spec.rb:24 # reboot task accepts a message
Finished in 11 minutes 33 seconds (files took 2.01 seconds to load)
14 examples, 0 failures
```
Tested manually on PE 2021.0.0 and the reboot task and plan can be run successfully
> (MODULES-10963) remove win32-process on Puppet 7

- tasks/last_boot_time_nix.sh
When doing 'last -1 reboot', the end of this line will show the current time on some platforms, since it shows both the start and end time of the session. Since the plan is simply comparing the raw string to see if we've rebooted, this makes it think we've always rebooted, since the end of this string changes every second. This commit slices off the end time, leaving only the login time.
> (MODULES-11149) Modify result of 'last' to remove current time

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for Windows Server 2008 and 2008 R2 was removed. 
Support for Windows 7 and 8 was removed.
Support for AIX 5.3 and 6.1 was removed.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Dropped support for Windows(7,8, 2008 Server & 2008 R2 Server) and AIX (5.3, 6.1)

- .rubocop_todo.yml
- spec/unit/task/init_spec.rb
Fixing CI failure due to rubocop
```
Split RSpec/FilePath into RSpec/SpecFilePathSuffix and RSpec/SpecFilePathFormat. RSpec/FilePath cop is enabled by default, the two new cops are pending and need to be enabled explicitly. (@ydah)
```
Mention any related issues or pull requests.
> [CAT-1382] : Fixing CI failure due to rubocop

- .rubocop_todo.yml
- spec/acceptance/reboot_with_custom_message_spec.rb
- spec/unit/task/reboot_spec.rb
- tasks/init.rb
Fixing rubocop failures
Add any additional context about the problem here. 
Mention any related issues or pull requests.
> (MAINT) - Fixing rubocop failures
