README.md
1. Remove any "what this affects" sections, except where particularly warranted.
2. Make sure that for each parameter, where applicable, there is a data type and a default value.
3. Make sure that for each parameter that's applicable, there is a note if the parameter is optional.
4. Make sure the links in the README work and are accurate.
5. Update the link in the Contributing section to point here: https://docs.puppetlabs.com/forge/contributing.html
6. General copyediting.
=> Updates README per DOC-1495

lib/puppet/provider/reboot/windows.rb, spec/unit/provider/reboot/windows_spec.rb
- Use WMI to query the CCM_ClientUtilities class of the CCM ClientSDK
namespace to call the DetermineIfRebootPending WMI method.  The object
returned contains a ReturnValue and two flags RebootPending and
IsHardRebootPending
See the Configuration Manager Client SDK WMI reference for more info:
https://msdn.microsoft.com/en-us/library/jj885518.aspx
Only unit tests are included since writing an acceptance test requires
additional dependencies that are difficult to install in this context.
To manual test, install the System Center Configuration Manager Client
=> (MODULES-2659) Detect CCM pending reboot state

CHANGELOG.md, CONTRIBUTING.md, README.md, metadata.json
Update all references from puppetlabs to puppet
=> (MODULES-3356) Branding Name Change

.sync.yml, Gemfile
- Nokogiri was originally added as a dependency in
0643a1c57c71e0f40db1adbaa6a9ce50a5413b27 as part of
https://github.com/puppetlabs/puppetlabs-reboot/pull/32
While at that time, it was a direct dependency of rspec-puppet
which itself was a dependency of rspec-system-puppet and
rspec-system-serverspec, it was also unnecessary to add the
transitive dependency directly to the Gemfile. That is typically
only necessary when the transitive dependency needs a stricter
versioning requirement due to conflicts with the code in the
parent project or other dependencies.
- When rspec-system, rspec-system-puppet, rspec-system-serverspec
and other unused gems were removed approximately 6 months later in
935144626d817dc1f24ccfa15240c03b94b8d8c9 as part of …
=> (maint) Remove Nokogiri from Gemfile

tasks/init.json, tasks/init.rb
Created a task for rebooting machines ad-hoc.  First task, feedback encouraged.
=> Added `reboot` task

.rubocop.yml, .sync.yml, .travis.yml
=> Modules 5896 fix for rubocop

tasks/init.json, tasks/init.rb
This fixes CVE-2018-6508. Code injections was possible on windows and has been confirmed fixed. Couldn't get code injection working on UNIX platforms but it has been hardened anyway.
=> Improve parameter validation

README.md
README.md currently states provider is determined by kernel fact.
The code suggests it is the operatingsystem instead.
=> Update README.md to clarify provider restriction

metadata.json
=> [FM-6968] Removal of unsupported OS from reboot

spec/spec_helper_acceptance.rb
=> (MODULES-7417) Addition of support for Debian 9 and Ubuntu 16.04 and 18.04

metadata.json
Fix the issues url in line with other Puppet modules.
=> (maint) Fix broken link in metadata file

CHANGELOG.md, metadata.json
The commit prepares the module for the 2.1.0 release.
=> (MODULES-8091) Prep module for 2.1.0 release

tasks/last_boot_time_win.ps1
This resolves an issue where the precision for last boot can cause you to get stuck in an infinite reboot loop if the machine reboots quickly within the same minute.  Go here for more info https://tickets.puppetlabs.com/browse/MODULES-8353
=> (MODULES-8353) Infinite reboot wait loop bug

spec/unit/provider/reboot/windows_spec.rb
to facilitate more complete test output from our unit tests.
=> (WIN-280) add skip() unless pattern to tests

metadata.json, spec/spec_helper_acceptance.rb
Add support on Debian10
pdk version: `1.11.1`
=> pdksync - Add support on Debian10

metadata.json, spec/spec_helper_acceptance.rb
=> (FM-8700) - Addition of Support for CentOs 8

.sync.yml, .travis.yml, Gemfile, Rakefile, appveyor.yml, metadata.json, spec/spec_helper.rb
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
=> (IAC-365) updating tokens and dataset for honeycomb

CHANGELOG.md, README.md, REFERENCE.md, metadata.json
=> (IAC-563) Release Merge back v3.0.0

.rubocop.yml, .sync.yml, Gemfile, metadata.json, spec/acceptance/tasks/init_spec.rb
A few items that were missed from the initial PR: https://github.com/puppetlabs/puppetlabs-reboot/pull/244
=> (IAC-140) Litmus port cleanup

metadata.json, provision.yaml
(IAC-890) - Implement CentOS 8 travis tests
pdk version: `1.18.0`
=> pdksync - (IAC-890) - Implement CentOS 8 travis tests

metadata.json
=> (IAC-1116) - updating authorname to puppetlabs

.github/pull_request_template.md, .github/workflows/weekly.yml, README.md, metadata.json
Removal of any offensive or inappropriate terminology from the code base.
=> (IAC-1003) - Removal of inappropriate terminology

CHANGELOG.md, metadata.json
=> (IAC-1247) Release version 3.1.0 merge back

spec/acceptance/tasks/init_spec.rb, spec/plans/init_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance_local.rb
=> (IAC-1527) remove bolt filters

.github/workflows/auto_release.yml, .github/workflows/spec.yml, Gemfile, metadata.json, spec/spec_helper.rb
PDK Update for auto release prep workflow
pdk version: `1.18.1`
=> pdksync - PDK Update for auto release prep workflow

.github/workflows/nightly.yml, .github/workflows/spec.yml, examples/sample.pp, metadata.json, plans/init.pp
(Maint) PDK Update
pdk version: `2.3.0`
=> pdksync - (Maint) PDK Update

spec/acceptance/tasks/init_spec.rb, spec/spec_helper_acceptance_local.rb
Provide a detailed description of all the changes present in this pull request.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (CAT-2050) Fix reboot task specs

.github/workflows/release.yml, .gitignore, .pdkignore, .rubocop.yml, .vscode/extensions.json, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
(PF-3525) - pdk update for module
pdk version: `3.2.0`
=> pdksync - (PF-3525) - pdk update for module

metadata.json
Add Ubuntu 24.04 support
Mention any related issues or pull requests.
=> (CAT-2119) Add Ubuntu 24.04 support
